import './globals.css'
import type { Metadata } from 'next'
import { 
  Roboto_Flex as Roboto,
  Bai_Jamjuree as BaiJamjuree,
 } from 'next/font/google'
import { DefaultProvider } from '@/components/default-provider'
import { SessionProvider } from 'next-auth/react'
import { AppProps } from 'next/app'
import { Session } from 'next-auth'

 const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' })
 const baiJamjuree = BaiJamjuree({
   subsets: ['latin'],
   weight: '700',
   variable: '--font-bai-jam-juree',
 })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface propsApp {
  children?: React.ReactNode,
  session?: Session | null;
}

export default function RootLayout({children, session}: propsApp) {
  return (
    <html lang="en">
      <body 
        className={`${roboto.variable} ${baiJamjuree}`}
      >
        
          <DefaultProvider>
            {children}  
          </DefaultProvider>
        
      </body>
    </html>
  )
}
